APP_STL := gnustl_static
APP_ABI := all
APP_ABI:= armeabi-v7a arm64-v8a
APP_CPPFLAGS += -frtti
APP_CPPFLAGS += -fexceptions
APP_CPPFLAGS += -DANDROID
APP_OPTIM := release
APP_PLATFORM=android-8
LOCAL_ARM_MODE := thumb